apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - mappingMethod: claim
      name: cognito
      openID:
        claims:
          email:
            - email
          name:
            - name
          preferredUsername:
            - preferred_username
        clientID: {{ .Values.clientId}}
        clientSecret:
          name: openid-client-secret-cognito
        extraScopes: []
        issuer: "https://cognito-idp.{{ .Values.region }}.amazonaws.com/{{ .Values.userPoolID }}"
      type: OpenID
